### ISSUE TITLE
Cannot Rename Weapons Or Tools

### ISSUE THREAD

**Issue by joeyman2525** [Pocketkid2/Name#2]
Hello! I have recently discovered an issue where i cannot rename netherite tools or gear, i have to name diamond tools and gear and combine them. Please update the plugin so it recognizes Netherite tools, weapons, and gear as items. Thanks!

**Comment by Pocketkid2** [comment]
I apologize for how long it took me to see this, I've just updated the plugin to 1.18 and it seems to work just fine for netherite. Let me know if you have any other problems!
